### ISSUE TITLE
Ability to record Glory and make Reputation rolls directly from character sheet

### ISSUE THREAD

**Issue by Orlanth-Rex** [mkscho63/sta#101]
**Is your feature request related to a problem? Please describe.**
Have to use a workaround when using Reputation instead of Discipline when rolling; having to record Glory in an ad-hoc note section.

**Describe the solution you'd like**
A field on the sheet to record Glory acquired.
Ability to roll for Glory as per STA Klingon Empire rulebook and add newly acquired Glory to total.
A ‘tickable’ Reputation field on the sheet

**Describe alternatives you've considered**
To use reputation: temporarily adjusting a Discipline to match.

**Additional context**
None.

**Comment by tokeidlom** [comment]
Reputation roll to be included for 2e character sheets in v1.2.4.
I don't have the Klingon book though, can you explain how glory works?

**Comment by Orlanth-Rex** [comment]
Glory is the same as Acclaim in 2e.

**Comment by Orlanth-Rex** [comment]
Would it clutter the character sheet too much to add somewhere to record Acclaim (Glory) and Reprimand (Dishonour)? Could just be a free text box to record a number rather than a tracker.

**Comment by tokeidlom** [comment]
Weirdly there isn't anywhere to record this on the official forms that Modiphius produced either, on either the main sheet or on the personal log.... I wonder whether an enhancement could be for a 2nd tab on the character sheet for the personal log, and it could be captured there? The main sheet itself is already quite busy.

**Comment by tokeidlom** [comment]
Did the latest update sufficiently resolve this issue? There's a space on the character sheet to record it, and the side bar roller can roll any combo you can think of (so 7 and reputation for example). If so I'll close this issue.

**Comment by Orlanth-Rex** [comment]
The side bar roller is great, but for reputation rolls there is the following (p.171 2e core book):

> 3. Assemble Dice Pool: Roll a number of d20s equal to the number of positive influences you have. Unlike a normal task, **there is no maximum number of d20s for this roll.**

Although in reality there are only 7 items in the list of positive influences, so a practical limit of 7 dice in the dice pool here?

**Comment by tokeidlom** [comment]
The sidebar roller now allows for free input of dice numbers, does this now meet your requirements?

**Comment by Orlanth-Rex** [comment]
That's perfect, thanks!
