### ISSUE TITLE
Character Variables Names for Export to PDF

### ISSUE THREAD

**Issue by gstrange42** [mkscho63/sta#105]
I'm trying to build the Mapping for the Export to PDf Module. I have looked all over and I can't find a list of variables for the Characters. I think I have some of the mappings correct however I have no clue as to what the others are. If you can provide a list that would be grand.

Here is what I have so far that I think is correct.

[
{
        "pdf": "Name", "foundry": @sta.actor.character.name ]},
        "pdf": "Species", "foundry": @sta.actor.character.species ]},
        "pdf": "Rank", "foundry": @sta.actor.character.rank ]},
        "pdf": "Environment", "foundry": @sta.actor.character.environment ]},
        "pdf": "Upbringing", "foundry": @sta.actor.character.upbringing ]},
        "pdf": "Assignment", "foundry": @sta.actor.character.assignment ]},
        "pdf": "Traits", "foundry": @sta.actor.character.traits ]},

        "pdf": "Control", "foundry": @sta.actor.character.attribute.control]},
        "pdf": "Daring", "foundry": @sta.actor.character.attribute.daring ]},
        "pdf": "Fitness", "foundry": @sta.actor.character.attribute.fitness ]},
        "pdf": "Insight", "foundry": @sta.actor.character.attribute.insight ]},
        "pdf": "Presence", "foundry": @sta.actor.character.attribute.presence ]},
        "pdf": "Reason", "foundry": @sta.actor.character.attribute.reason ]},

        "pdf": "Command", "foundry": @sta.actor.character.discipline.command ]},
        "pdf": "Conn", "foundry": @sta.actor.character.discipline.conn ]},
        "pdf": "Security", "foundry": @sta.actor.character.discipline.engineering ]},
        "pdf": "Engineering", "foundry": @sta.actor.character.discipline.medicine]},
        "pdf": "Science", "foundry": @sta.actor.character.discipline.science ]},
        "pdf": "Medicine", "foundry": @sta.actor.character.discipline.security ]},

        "pdf": "Reputation", "foundry": @'sta.actor.character.reputation ]},

        "pdf": "Value 1", "foundry": @name ]},
        "pdf": "Value 2", "foundry": @name ]},
        "pdf": "Value 3", "foundry": @name ]},
        "pdf": "Value 4", "foundry": @name ]},

        "pdf": "Determination 3", "foundry": @name ]},
        "pdf": "Determination 2", "foundry": @name ]},
        "pdf": "Determination 1", "foundry": @name ]},

        "pdf": "Talent 1", "foundry": @name ]},
        "pdf": "Talent 2", "foundry": @name ]},
        "pdf": "Talent 3", "foundry": @name ]},
        "pdf": "Talent 4", "foundry": @name ]},
        "pdf": "Talent 5", "foundry": @name ]},

        "pdf": "Focus 1", "foundry": @name ]},
        "pdf": "Focus 2", "foundry": @name ]},
        "pdf": "Focus 3", "foundry": @name ]},
        "pdf": "Focus 4", "foundry": @name ]},
        "pdf": "Focus 5", "foundry": @name ]},
        "pdf": "Focus 6", "foundry": @name ]},
        "pdf": "Focus 7", "foundry": @name ]},
        "pdf": "Focus 8", "foundry": @name ]},
        "pdf": "Focus 9", "foundry": @name ]},
        "pdf": "Focus 10", "foundry": @name ]},

        "pdf": "Injuries 1", "foundry": @name ]},
        "pdf": "Injuries 2", "foundry": @name ]},
        "pdf": "Injuries 3", "foundry": @name ]},
        "pdf": "Injuries 4", "foundry": @name ]},

        "pdf": "Stress 1", "foundry": @name ]},
        "pdf": "Stress 2", "foundry": @name ]},
        "pdf": "Stress 3", "foundry": @name ]},
        "pdf": "Stress 4", "foundry": @name ]},
        "pdf": "Stress 5", "foundry": @name ]},
        "pdf": "Stress 6", "foundry": @name ]},
        "pdf": "Stress 7", "foundry": @name ]},
        "pdf": "Stress 8", "foundry": @name ]},
        "pdf": "Stress 9", "foundry": @name ]},
        "pdf": "Stress 10", "foundry": @name ]},
        "pdf": "Stress 11", "foundry": @name ]},
        "pdf": "Stress 12", "foundry": @name ]},
        "pdf": "Stress 13", "foundry": @name ]},
        "pdf": "Stress 14", "foundry": @name ]},
        "pdf": "Stress 15", "foundry": @name ]},
        "pdf": "Stress 16", "foundry": @name ]},
        "pdf": "Stress 17", "foundry": @name ]},
        "pdf": "Stress 18", "foundry": @name ]},
        "pdf": "Stress 19", "foundry": @name ]},
        "pdf": "Stress 20", "foundry": @name ]},
        "pdf": "Stress 21", "foundry": @name ]},
        "pdf": "Stress 22", "foundry": @name ]},
        "pdf": "Stress 23", "foundry": @name ]},
        "pdf": "Stress 24", "foundry": @name ]},

        "pdf": "Weapon Name 1", "foundry": @name ]},
        "pdf": "Weapon Qualities 1", "foundry": @name ]},
        "pdf": "Weapon Dice 1", "foundry": @name ]},
        "pdf": "Weapon Name 2", "foundry": @name ]},
        "pdf": "Weapon Qualities 2", "foundry": @name ]},
        "pdf": "Weapon Dice 2", "foundry": @name ]},
        "pdf": "Weapon Name 3", "foundry": @name ]},
        "pdf": "Weapon Qualities 3", "foundry": @name ]},
        "pdf": "Weapon Dice 3", "foundry": @name ]},

        "pdf": "Other Equipment 1", "foundry": @name ]},
        "pdf": "Other Equipment 2", "foundry": @name ]},
        "pdf": "Other Equipment 3", "foundry": @name ]},
        "pdf": "Other Equipment 4", "foundry": @name ]},
        "pdf": "Other Equipment 5", "foundry": @name ]},
        "pdf": "Other Equipment 6", "foundry": @name ]},
        "pdf": "Other Equipment 7", "foundry": @name ]},
        "pdf": "Other Equipment 8", "foundry": @name ]

]

**Comment by tokeidlom** [comment]
There are these:
    "notes": "",
    "assignment": "",
    "environment": "",
    "milestones": "",
    "rank": "",
    "reputation": ,
    "species": "",
    "stress":
    "upbringing": "",
    "traits": ""
  "items": [],
  "effects": [],

Ok if I close this issue?

**Comment by gstrange42** [comment]
Sure
