### ISSUE TITLE
New Maintainer?  Open up to co-maintainer?

### ISSUE THREAD

**Issue by WesWedding** [mkscho63/sta#113]
Hi there,

Almost all open source projects get to a point where the original maintainer doesn't really have the time or interest required to keep a project going, and it feels like this project has been there for a while.  I think it would be very helpful to the users of this system if either a 2nd maintainer is allowed to step in and assist or the project gets handed off completely in a clean manner and can address the inevitable accumulation of edge cases and weird issues caused as Foundry continues to pump out major new versions.

Eventually someone is going to fork this repo and publish it, and that just makes things unnecessarily messy.  I've personally been [using my own Plugin](https://foundryvtt.com/packages/sta-enhanced) to clean up the system rather than try to fix the system directly (because PRs seem like a waste of effort right now), and another individual out there has their own [Second Edition fork](https://github.com/ELH-mk1/sta2e) fork in the works, as well.

**Comment by mkscho63** [comment]
Thank you for calling this out, I agree. I have not given this the attention it needs especially around the 2e STA drops. I have added CalinStar, who has done the 2e support in this system up till now, as a collaborator to help remove some of the bottleneck I've been. I'll continue to help out however I can but at least now there will be another person who has been more active recently with more access. As other people submit changes and express interest, we can look at adding additional people too. Thanks again for the feedback!

**Comment by tokeidlom** [comment]
I'm excited to be in board. Hopefully we can give this project the attention it deserves between us all. Unless anyone objects I am closing this issue for now, if there are any further changes needed to can reopen or raise a new issue. Hope that's ok with everyone.
