### ISSUE TITLE
Chat Card Refinments Proposal

### ISSUE THREAD

**Issue by WesWedding** [mkscho63/sta#117]
**Is your feature request related to a problem? Please describe.**
I got really annoyed having to ask my players to clarify if they were clicking Talents or Values to share with me, since there's no labelling on the cards.  So I decided that was a friction point I wanted to address in my STA plugin, with an eye to eventually suggesting the changes here.

The mix of business logic and raw HTML in the JavaScript was also suboptimal from a maintenance perspective, in my opinion, so I decided to tackle a refactor so that the View and Model layers were a little more separated and more aligned by the standards being set by the official D&D and PF2E systems.

**Describe the solution you'd like**
A more uniform approach to Chat Cards in general, especially with Item chat cards and labeling.  This is what my implementation currently appears like.

![chat-card-update](https://github.com/user-attachments/assets/a027c24a-6e5e-4760-ae01-9b2f182cd122)

My intent was to tackle issues I see with the Task chat cards sometime in the future.  But if it's likely that I can begin porting this work over and get it committed, I can change priorities to focusing on a feature update here.

**Additional context**
Given [my own update pushed today](https://github.com/WesWedding/sta-enhanced/releases/tag/v0.1.7) and a[ convo I saw on Discord](https://discord.com/channels/170995199584108546/753726151985332266/1266497471312433164), I am hopeful in potentially getting to submit a PR that will port these changes to this system directly.

**Comment by tokeidlom** [comment]
That looks awesome, I think it would be a worthy addition

**Comment by WesWedding** [comment]
Excellent, I'll see if I can't get this done sometime towards the end of the week.

**Comment by tokeidlom** [comment]
Happy with this Wes? Ok to close it out?

**Comment by WesWedding** [comment]
Yeah, looks like we've got this done at this point!
