### ISSUE TITLE
Roll Description of Complication range is mangled (English)

### ISSUE THREAD

**Issue by WesWedding** [mkscho63/sta#152]
**Describe the bug**
At some point the string for complication ranges in dice rolls got a little mangled.

It is now `Complication range20` instead of something cleaner.

**To Reproduce**
1. Open a character sheet.
2. Click Perform task.
3. Click Roll Dice.
4.  Observe chat message.

**Expected behavior**
The string displayed on the roll used to be: `Complication range is 20+`

**Screenshots**

![image](https://github.com/user-attachments/assets/b1865137-5c53-477f-a79a-cc8578943cdc)
![image](https://github.com/user-attachments/assets/6831a069-13b9-4c9e-b824-216ad6cdb835)

**Desktop:**
 - OS: Windows
 - Browser Firefox and FoundryVTT client
 - Version: 1.3.0

**Additional context**
The version I see the old text in is 1.2.3

**Comment by WesWedding** [comment]
Comparing those screens, it seems like font size changed, too.  Might be an illusion (two different browsers for each shot).

**Comment by tokeidlom** [comment]
There are also two colons with target there. I think one in the code and one in the language file.

**Comment by tokeidlom** [comment]
Looks like the 'is' was lost in the last update a week ago, I mistakenly added a new translation with the same name string.

The plus was lost as part of the chat card update in commit 550b906871c5da80cb461f52f5014279d1e76235

I'll fix both of those and add them to the latest PR.

**Comment by tokeidlom** [comment]
The extra : and addition of + and is addressed in:
7272e2e385f6f4bd4bfd8308474bb8dfd7a5a43e

**Comment by tokeidlom** [comment]
That update has been released now.
