### ISSUE TITLE
Typo: Persuasion talent is listed as "Persuation"

### ISSUE THREAD

**Issue by LonePaladin** [mkscho63/sta#154]
No additional details needed, just reporting a misspelled entry.

**Comment by tokeidlom** [comment]
Huh, no way, thats in the 1e focuses, that must have been wrong for years!
Glad I got it right in the 2e version :)

Fix pushed here:
https://github.com/mkscho63/sta/pull/151/commits/63f824be0a3069da497ba856d8f9c192b8c4d81e

**Comment by tokeidlom** [comment]
That update has been released now, should be all good.
