### ISSUE TITLE
Character Sheet

### ISSUE THREAD

**Issue by Ghrimvold** [mkscho63/sta#155]
Hello,
I was just curious as to why your character sheet looks different than the one we use. I realize that the image of ours has an incomplete Actor sheet, but the sheet format is different.

Yours:
![2024-09-25 14_28_54-Window](https://github.com/user-attachments/assets/37e22e76-4949-4fce-99a5-277866475b31)

Ours:
![2024-09-25 13_25_30-Window](https://github.com/user-attachments/assets/39681e1d-bc93-478f-96ad-b25ee5ecef3c)

Thank you

**Comment by tokeidlom** [comment]
That looks like you have the STA enhanced module installed in the second picture. If you disable that your character sheet will look the same.

**Comment by tokeidlom** [comment]
I don't think there's anything further needs doing here?
