### ISSUE TITLE
STA system not working with tabbed chatlog

### ISSUE THREAD

**Issue by Felderburg** [mkscho63/sta#163]
Hello, the tabbed chatlog module (https://github.com/cswendrowski/FoundryVTT-tabbed-chatlog) is not working properly for me. When I start a fresh world with this STA system, the chat populates with the default 'new gm info' stuff. If I roll, it also appears.

However, when I add the tabbed chatlog module: 1. all of those items do not appear in any of the chat tabs, and 2. rolls made after that do not appear in any of the tabs, although the notification that a roll was made appears over the chat icon in the toolbar.

When I remove the module, the initial gm info as well as any rolls made then appear in the default chat.

I have not made, as far as I know, any changes to any default settings the system or the modula have.

**Comment by Felderburg** [comment]
![sta foundry rolls only appear after tabbed is off](https://github.com/user-attachments/assets/a33d8a6f-f995-47ac-be1d-99335eec5718)
![sta foundry a roll notification appears in tabbed](https://github.com/user-attachments/assets/9bf17420-7e7b-42b8-af36-a9bb206274de)
![sta foundry default after adding tabbed chatlog](https://github.com/user-attachments/assets/778c64bb-4952-4292-a30a-99c7b543f24d)
![sta foundry adding tabbed chatlog_module url](https://github.com/user-attachments/assets/3a3d3075-4e57-4261-9667-df47987e50e8)
![sta foundry default start](https://github.com/user-attachments/assets/4948d1cb-f7d1-4fb1-a37f-59213e88a123)

**Comment by tokeidlom** [comment]
Has it ever worked for you? A quick look at that module page shows it hasn't been updated in 3 years and it's last compatible foundry version as V9, so not sure there is anything we could/ should do to help with that.

**Comment by Felderburg** [comment]
Sorry for the lack of response to this question, I apparently didn't see it in my email (just the marked complete notification). I only started using it at the time I posted this issue. The tabbed chat module seemed to be the most popular recommended, and my GM uses it (in another system), so I had hoped it would work. I will test the fix later.
