### ISSUE TITLE
Cannot Create NPCs with attribute values below 7

### ISSUE THREAD

**Issue by Mrafala** [mkscho63/sta#171]
I'm having the same issue that Braste reported on Feb 13. Looks like the problem has returned? Is there an NPC sheet template we should be using instead of the normal PC one?

_Originally posted by @Mrafala in https://github.com/mkscho63/sta/issues/102#issuecomment-2566284312_
            
> **Describe the bug** I cannot crete NPCs with attribute values below 7, because the character sheet won't let me.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Try to enter a number below 7 in an attribute.
> 
>     2. Leave the cell
> 
> 
> **Expected behavior** We must be able to enter values below 7.

**Comment by tokeidlom** [comment]
There is no specific NPC sheet, but if you go to the settings you can check the box to ignore 7-12 normal rules, you can then put numbers between 0-99 in the boxes of the standard sheet.

**Comment by Mrafala** [comment]
> There is no specific NPC sheet, but if you go to the settings you can check the box to ignore 7-12 normal rules, you can then put numbers between 0-99 in the boxes of the standard sheet.

Thank you!
