### ISSUE TITLE
Allow for manually adding stress

### ISSUE THREAD

**Issue by XT-19** [mkscho63/sta#20]
I think it would be nice if we had the opportunity to manually add stress. For example, the human resolute talent calls for increasing the maximum stress for a character.

**Comment by mkscho63** [comment]
Just to note, but if you add a Talent called Resolute to your Talent list on a character, it will add 3 to that character's maximum stress to account for this specific situation. Although I have been looking at adding some customizing to the size of the stress bar so the feedback is definitely taken here.

**Comment by XT-19** [comment]
Ohhhh, thank you for the note :)

**Comment by Ryach** [comment]
Not only manual customisation of stress but could you polease add also manual customisation of ship shield size

**Comment by tokeidlom** [comment]
Stress and shields modification option added in release 1.2.1
