### ISSUE TITLE
Ability to make generic 2d20 checks without having a specific actor tied to it

### ISSUE THREAD

**Issue by mkscho63** [mkscho63/sta#27]
The main idea here is to allow people to make checks for generic crew on a ship, where they input an attribute/discipline instead of using the preset values or having to create a whole character for it.

Also it's a pretty big miss that you are unable to make a 2d20 roll without using the actor sheet, so I need to find a way to allow that (besides having it on the starship sheet only). That way if there is a random npc that needs to make a check, the GM can make one on the fly.

**Comment by tokeidlom** [comment]
I've included this in the latest PR 8D 1.2.4 should close this issue!

**Comment by tokeidlom** [comment]
And... Done:)
