### ISSUE TITLE
Small Request: Momentum Display Minimize

### ISSUE THREAD

**Issue by Bluejeanjedi** [mkscho63/sta#29]
I would love to be able to minimize/hide the momentum tracker. There are already mods out there that hide everything (for TV/display gaming). However those mods don't seem to affect the momentum tracker.

Other than that, great work! Love it so far.

**Comment by mkscho63** [comment]
This should be there now in v1.0.7. You can still see just the edge of the trackers, which was a personal design choice on it (not used to not having a designer tell me what things should look like heh). I hope that helps and meets the need you have here. Let me know if there is something else I can change to help out!
