### ISSUE TITLE
TOS-Style UI

### ISSUE THREAD

**Issue by Armandeus66** [mkscho63/sta#30]
Thank you for creating this!!
I'm sure it's not a priority, but it would be neat-o to also have a TOS-style UI option for those of us who play in that era.
Thank you!

**Comment by tokeidlom** [comment]
I've looked into this, there doesn't seem to be a way to include multiple styles easily within a foundry system. The options at the moment are the default skin, or to use the LCARS UI module. If anyone is creative and wants to design a new module I'd be happy to get it hosted, but my own design skills are limited. I'll close this issue for now as I don't think we will be able to progress anything with it. Sounds cool though, I'd love for there to be a collection of skins available for it!
