### ISSUE TITLE
Possible Update Issue: Missing token art

### ISSUE THREAD

**Issue by Bluejeanjedi** [mkscho63/sta#34]
**Describe the bug**
All token images just show a "broken image" link. No directories have changed. Is this possibly due to the update?

**To Reproduce**
1. Go to Actor tab
2. Click on Folder containing tokens
3. Scroll down to any token

**Expected behavior**
See assigned images with the tokens.

**Screenshots**
![error](https://user-images.githubusercontent.com/77998100/108012846-fe485a00-6fcf-11eb-8774-e67775e95508.png)

**Desktop (please complete the following information):**
 Windows 10 (most recent update)

**Comment by mkscho63** [comment]
That is really odd, I don't know what I would have done that would break that especially since it isn't broken on my own machine. It makes me wonder if something went wrong with the package upload to Github. I'll take a look into this. Thanks for the details.

**Comment by Bluejeanjedi** [comment]
It very well could be a coincidence of something else that updated. I'm moving some files/images around and I'll keep an eye on it. Nothing to worry about then.
