### ISSUE TITLE
Weapon Qualities and Effects in Chat message

### ISSUE THREAD

**Issue by theczarek** [mkscho63/sta#36]
**Describe the solution you'd like**

I'd like to see weapon qualities and effects when i roll weapon damage (for perdonal and ship weapon alike)
Also a drop down description of items and weapon on the sheet would be useful. Behavior similar to talents.

**Comment by mkscho63** [comment]
I really like this idea, this is my next goal.

**Comment by mkscho63** [comment]
I have fixed the changes with 1.1.10 that broke this in the past. If the issue returns please feel free to bring this up again. Thanks for the report and have a great time gaming!
