### ISSUE TITLE
Two small bug

### ISSUE THREAD

**Issue by Mizy78** [mkscho63/sta#41]
1. On smallcraft sheet I cannot enter a value less than 7 for the systems item.

2. Playlist Tab is not displayed. Only the orange screen.

**Comment by Ryach** [comment]
not only small craft but also normal craft cannot have less than 7

**Comment by Mizy78** [comment]
> not only small craft but also normal craft cannot have less than 7

In Starter Set adventure is shuttlecraft, that have 5 and lower.

**Comment by mkscho63** [comment]
The issue with small craft and starships should have been fixed in the release yesterday, let e know if it is still an issue.

**Comment by Ryach** [comment]
yes, its fixed I didnt see update coming ;)

**Comment by mkscho63** [comment]
I'm currently not seeing the issue with the playlist anymore, is it still occurring for you?
