### ISSUE TITLE
Ship card update

### ISSUE THREAD

**Issue by Ryach** [mkscho63/sta#43]
Is it possible to add a breach system to the ship's card?
maybe in a similar style to shields markers, but with a list of system and spaces on right where breaches can be marked

**Comment by mkscho63** [comment]
So there is a field to the side of the values for systems for recording the number of breaches that that system has sustained. Is there something more that would be helpful? I'll admit, I have not done a ton of starship combat so I have never had to actually track breaches myself, let me know if that could be implemented any better.
![image](https://user-images.githubusercontent.com/9925376/130541781-f002eeb3-d929-46e1-af1c-c6ec72f84518.png)

**Comment by Ryach** [comment]
This is good idea but,  maybe it is possible to create list similar to tallents, with Name and Description, when will be drag on the ship each will automatically add breach to proper system?

**Comment by Ryach** [comment]
I given some extra thought, I think maybe if it is not too complicated:
A):  Add three dots similar to the shields (first will be IMPACT, second DAMAGED, third DISABLED,
B): In damage report if there can be opened description similar to Talents will this be enough? 
![Screenshot 2021-09-23 180817](https://user-images.githubusercontent.com/6523648/134552623-9a79a31c-06e6-4663-8636-6be8939450ee.png)

**Comment by tokeidlom** [comment]
For PartA I think we now have something workable, if you check the images in https://github.com/mkscho63/sta/pull/151, that seems like the most space efficient way of handling that.

That should have addressed both parts of the request.
