### ISSUE TITLE
Smallcraft Power and Shield calculation

### ISSUE THREAD

**Issue by xanstin** [mkscho63/sta#45]
**Describe the bug**
Per the rules 
SHIELDS: Small Craft have Shields equal to half their normal values; add together Structure and Security, then halve the total, rounding down.
POWER: Small Craft have much smaller power plants than full-size starships, and only generate Power equal to half their Engines score (rounding up).

**To Reproduce**
Open Default Smallcraft Sheet

**Expected behavior**
Values should be halved.

**Comment by mkscho63** [comment]
Oh good call, this is getting fixed now. Can't believe I never noticed that.
