### ISSUE TITLE
Some missing options for ship weapon items

### ISSUE THREAD

**Issue by xanstin** [mkscho63/sta#48]
![image](https://user-images.githubusercontent.com/26841771/133897070-696ae7c3-aac8-4fac-9575-a517911dbbf9.png)

Need a option for Tractor Beam Strength maybe with an override for damage number since if you leave blank it shows NaN, One can put in other cargo but it is considered a Weapon and an Attack by the rules
No Persistent field for Plasma Weapons like Romulan Plasma Torpedoes are Persistent 8

Also carrying over from https://github.com/mkscho63/sta/issues/36. Also add the weapon qualities to the chat card for ships.

**Comment by tokeidlom** [comment]
Looking at the rules for tractor beams, they are describes as weapons, but the rules for them do not roll damage (at least in 2e). As such I would suggest they are in the proper place as items.
I have added persistent to the 1e weapons sheet should go out in issue 1.2.4.
Thanks for the input.
