### ISSUE TITLE
Item Folders Can't Delete

### ISSUE THREAD

**Issue by Bluejeanjedi** [mkscho63/sta#55]
I'm experiencing an odd little issue. I was organizing my item folders (and subfolders) with items made in FVTT. 
Example: Weapons --> Melee      Weapons --> Ranged 

Oddly enough, while in the middle of making these, all the subfolders were kicked out of the main. No folder can be moved. And I cannot delete these folders or edit them in any way. 

I tried resetting and uninstalling the system module. There are no modules activated in this system. Any help welcomed, thanks.

![FolderProblem](https://user-images.githubusercontent.com/77998100/151270365-40ab1b42-5f07-414a-8b83-133c67d09ee7.png)

**Comment by mkscho63** [comment]
Is this still an issue, I suspect this might have been an issue in Foundry because I'm unable to recreate the issue in the current version (sorry for the extremely late response). Wanted to check before I closed the issue.
