### ISSUE TITLE
Weapon damage changes when opening a new character sheet.

### ISSUE THREAD

**Issue by Moofaa** [mkscho63/sta#56]
When you have a character sheet open and then open another, the damage on weapons on the previous sheet are updating to use the new sheets stats. Repeatable. The change reverts if you close all the sheets.

Math-wise it appears to be applying the most recently opened characters Security rating to all damage on weapons on other character sheets.

Work-a-round: Close all sheets, and only have one sheet open at a time.

Can confirm this is happening on:
Foundry 8.9 / STA 1.1.3
Foundry v9 / STA 1.1.5

**Comment by hiddenkrypt** [comment]
This issue was resolved by  merge request 61 on Mar 2, and should be closed.

**Comment by tokeidlom** [comment]
As mentioned, this is now fixed, so closing, thanks all.
