### ISSUE TITLE
Can't Click Text Box

### ISSUE THREAD

**Issue by Bluejeanjedi** [mkscho63/sta#60]
Here's an odd bug that keeps popping up.

On occasion I can no longer click in the box to edit text. This is for any box, from talents to compendium entries. Once one box is locked out, they all are. I removed all modules in case there was a conflict. Sometimes it's on the 5th edit, sometimes the 2nd.

UPDATE: I discovered that if I go to another tab (like a web browser) and then click back on Foundry, I can click in boxes again. Eventually it stops letting me type in boxes, so I just have to click out, then back again.

UPDATE 2: It seems that the issue comes when I drag an item/talent I made onto the character sheet of an actor. As above, if I click off to another tab, then back to Foundry software, it fixes itself.

![Error](https://user-images.githubusercontent.com/77998100/155033441-a191fe6f-2627-44ec-b421-e9636af589f7.png)

**Comment by WesWedding** [comment]
Another way to reproduce:

1.  Add an item to a character sheet.
2.  Click the delete icon to remove it.
3. A Foundry VTT popup appears to confirm.  "Are you sure you want to delete..."
4. Click either OK or Cancel

Text boxes are now unresponsive to focus changes and are non-editable.

**Comment by tokeidlom** [comment]
Had this been resolved by the commits? If so I'll close this issue.
