### ISSUE TITLE
There is no character sheet option to include innate resistance

### ISSUE THREAD

**Issue by Chaosoverfiend** [mkscho63/sta#65]
**Is your feature request related to a problem? Please describe.**
When creating NPC characters there is no option in the character sheet to include innate resistance

**Describe the solution you'd like**
A way to include innate resistance without using an item

**Describe alternatives you've considered**
Create "armor" items to replicate innate resistance

**Comment by tokeidlom** [comment]
Would this be considered a trait and be noted there? I can't imagine a better way of including this other than as a type of armour, it acts in a similar way just against a specific type of damage / attack

**Comment by tokeidlom** [comment]
I have renamed the armor section to armor / resistance. Both of these things are treated similarly in STA and needing to look in two places for similar info you need isn't good design. Appreciate that this is a compromise, but one I hope you can live with?
