### ISSUE TITLE
Feature: NPC Ship Sheet

### ISSUE THREAD

**Issue by xanstin** [mkscho63/sta#70]
If possible add a place where you can roll ships crew from the ship for NPC Ships. Either a drop down with the 4 quality levels yielding a target number for rolls with the same popup as tasks for characters or free form with a attribute and discipline.

**Comment by xanstin** [comment]
This would be great.

**Comment by tokeidlom** [comment]
You can do this by adding some generic ships with required stats (or even some more specific ones, like Romulan / Klingon warbird) to the compendium, you can drag over as many as you need into the actor screen.

**Comment by tokeidlom** [comment]
https://github.com/mikira7/sta-macros

There is this macro that can achieve what you want, grab an npc ship from the compendia, click its token and then use this macro.

**Comment by MrNightwood** [comment]
This macro certainly does the trick, though I still feel like it'd be a nice feature to have built into the system, if for no other reason than the visual consistency of the rolls in the chat. The layout of the form created by the macro is very similar to what I'd hope for were this to be implemented. Having something like this built onto the sheet would allow for the skill level to be persistent and not have to be re-selected each time, and for the already selected system/department to carry over as well.

**Comment by tokeidlom** [comment]
Ok, so this is now included in the sidebar roller, can you check it out and let me know if it meets your requirement?
