### ISSUE TITLE
DiceSoNice does not display Task and Challenge rolls for other players

### ISSUE THREAD

**Issue by FabulistVtt** [mkscho63/sta#71]
**Describe the bug**
3D dice are only shown to the user initiating the Task or Challenge Roll, but no other users.

**To Reproduce**
1. Install and activate Dice So Nice!
2. Login with two users A and B
4. Have user A open a character sheet that they control and let them perform any Task or Challenge Roll with at least 1 die.
5. Observe display for user B
6. You'll see no dice animation, just the chat message of the result

**Expected behavior**
Dice rolls are shown for all users.

**System**
 - Foundry v9 Build 269
 - STA 1.1.6
 - Dice So Nice! 4.3.0

**Fix**
You just have to change two lines in roll.js. Replace both occurances of
`game.dice3d.showForRoll(r)`
with
`game.dice3d.showForRoll(r, game.user, true)`

**Comment by FabulistVtt** [comment]
It's still an issue with the recent STA 1.1.9, but the same fix still works.

**Comment by mkscho63** [comment]
Including this in with 1.1.10 which is currently on develop, please let me know if the issue persists and feel free to reopen the issue. I also took this as a chance to get rid of the "double dice roll sound" issue that's been around with dice so nice. Thanks so much for the report and the solution as well (making my life easy <3 ) and I hope this fixes your problem!
