### ISSUE TITLE
Development Continuing? (version question)

### ISSUE THREAD

**Issue by Bluejeanjedi** [mkscho63/sta#72]
Hey there. With the new version 10 growing closer for Foundry, I was curious if development was still happening with this app. I enjoy using it but want to make sure I know which version to halt at if this is the final version. Thanks in advance!

**Comment by mkscho63** [comment]
It will be updated, I have a week off of work coming soon and a laundry list of things I’ll try to get done, v10 compatibility is near the top of the list. I’d say hold off on upgrading for now but hopefully I have it upgraded before the end of august.

**Comment by Bluejeanjedi** [comment]
Awesome. Certainly, no rush, I appreciate the work! Just wanted to make sure I didn't break something. :)

**Comment by CoolcatFVTT** [comment]
Cool! No rush from me either, but looking forward to it :)
