### ISSUE TITLE
Alternate Styling?

### ISSUE THREAD

**Issue by gmmatt** [mkscho63/sta#74]
So this may go down as the dumbest and most pointless feature request ever, but is there a way to either get an unstyled UI and character sheet and/or a UI and character sheet with more of a classic Star Trek feel? Or a retro-modern Strange New Worlds type styling?

No hate, but I like to play in the classic era vs TNG, and I'm finding the TNG aesthetic so distracting to the experience that I'm shying away from actually using the system.

Again, dumb reason I know, but I thought I would mention it.

**Comment by CoolcatFVTT** [comment]
You try the LCARS UI by Fabulist or use it as a basis for your own TOS era mod for the STA system: https://foundryvtt.com/packages/sta-lcars-ui

**Comment by tokeidlom** [comment]
I've looked into this, there doesn't seem to be a way to include multiple styles easily within a foundry system. The best options at the moment are the default skin, or to use the LCARS UI module. If anyone is creative and wants to design a new module I'd be happy to get it hosted, but my own design skills are limited. I'll close this issue for now as I don't think we will be able to progress anything with it.
