### ISSUE TITLE
Allow Private Rolls from Perform Task/Challenge in Character/Ship Sheet

### ISSUE THREAD

**Issue by crm2099** [mkscho63/sta#75]
Hello

First of all, THANK YOU for your hard work on translating the STA system into Foundry VTT. This made our experience with this system so much better than using something generic.

Second, I am not sure if I am missing something, but the Perform Task/Challenge actions from the character sheets do not seem to interact with the Private/Public roll selections in the Log.
![image](https://user-images.githubusercontent.com/112741311/188254381-cd3d3b37-a5c1-4420-b1de-594b30e5f99c.png)

Regardless of your choice in the Chat Log, the rolls always come out open (offering the option to make them private afterwards, but that defeats the purpose. 

Hiding the rolls from the players is a key element in the GM's toolkit, I would love to have this in the STA system.

Also, looking forward to VTT version 10 compatibility as well.

Again, thank you so much for this system and taking the time to read this.

**Comment by TitanicViking** [comment]
Has this still not been addressed? I encountered a similar problem with the dune 2d20 system recently, & while star trek isnt nearly as intrigue heavy as that one is, it really makes it difficult on GMs to not be able to use sheets without ruining the plot for our players.

**Comment by mkscho63** [comment]
It has not been addressed yet. I need to figure out how to set the rolls on a character sheet to respect the selection here, but I'm not sure how to do that offhand.

**Comment by TitanicViking** [comment]
> It has not been addressed yet. I need to figure out how to set the rolls on a character sheet to respect the selection here, but I'm not sure how to do that offhand. I'll leave this issue open in case someone comes up with a solution (or at least as a reminder to me so I don't forget) but for the time being I can't resolve it.

Thanks for the reply. I did find a work around using the Hide Gm Rolls module, but it only forces invisible tokens on the canvas to Private for the GM only. So rolls from character sheets not invisible on the canvas are still public. 

Hopefully that helps in some way.

**Comment by tokeidlom** [comment]
STA System now supports the built in Self Roll and GM roll option when selected in the right hand dropdown menu, when rolling both from the character sheet and the sidebar (Spock) roller. Thank you for the issue suggesting it!
