### ISSUE TITLE
Weapon Rolling from Character Sheet throws Error

### ISSUE THREAD

**Issue by Aceman67** [mkscho63/sta#79]
To Reproduce: Attempt to roll weapon damage from character sheet

Log File Attached

[localhost-1665544200993.log](https://github.com/mkscho63/sta/files/9761171/localhost-1665544200993.log)
![log](https://user-images.githubusercontent.com/52718032/195241164-eb5642d2-3bad-4eea-8f64-5b577b67c7ca.png)

**Comment by mkscho63** [comment]
This is an issue with the code when DiceSoNice is turned on, should be an easy fix

**Comment by mkscho63** [comment]
Should be fixed in 1.1.10, I have it on the develop branch now, thanks for the report and let me know if it's still around!
