### ISSUE TITLE
1.1.9 breaks Extended Task sheet

### ISSUE THREAD

**Issue by iamthecrave** [mkscho63/sta#84]
After installing 1.1.9, Extended Tasks creation throws error "**Model Validation Error [Actor.name] may not be blank string"** when you enter information. Extended Task saves to Actor panel but with no data in it.

**To Reproduce**
1. Go to 'Actor' tab.
2. Click on 'Create Actor'
3. In "Create New Actor" dialogue enter title. In Type dropdown, choose "extendedtask". Click "Create New Actor."
4. In Extended Task dialogue box, enter Name. In Work, enter any number (ie. 2)
5. Error message will pop up.

**Expected behavior**
Expecting Extended Task dialogue to be pre-populated with values. Expecting Work Track to be prepopulated with at least a few numbers in it. Expecting to be able to enter information without throwing error message, Expecting to be able to save Extended Task. Expecting users to be able to click on it after it is created an see the information.
**Screenshots**
![image](https://user-images.githubusercontent.com/84590468/201535093-3f2ae2e2-ac78-429e-b97a-93a4f485ccc2.png)

![image](https://user-images.githubusercontent.com/84590468/201535138-407bdca8-7ed6-4013-ab26-11ca91a8d7fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (bug happens on Forge as well.)
 - Browser: Chrome 
Version 107.0.5304.107 (Official Build) (64-bit)

Foundry support info:
Foundry Virtual Tabletop: Version 10, 10.290
Game System: sta, 1.1.9
Active Modules: 1
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
GPU: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1400 x 1164 | Grid Size: 50 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 1 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 4

Actors: 54 | Items: 176 | Journal: 99 | Rollable Tables: 5 |
Playlists: 4 | Compendium Packs: 0 | Chat Messages: 518

**Additional context**
This is definitely a 1.1.9 bug. I rolled it back to 1.1.6 and was able to create Extended Tasks. However, 1.1.6. will not allow users to see Character Sheets by clicking on items in the Actor panel.

**Comment by iamthecrave** [comment]
Anybody have any thoughts on this?

**Comment by iamthecrave** [comment]
Hey @mkscho63 . I know this is a labour of love for you so I don't want to bug you. But, is there any progress on the Extended Task being fixed? Am I the only one experiencing it? Thanks for your time and effort. Won't bug you again.

**Comment by mkscho63** [comment]
I think this is the only report of this specific problem. Sorry for no response, I've been out with both variants of the flu since Christmas (heckin' unlucky) but I'm getting over them now. I do plan on fixing this problem and just have not gotten around to pushing the new version. I'm gonna try to tackle it this weekend though. No worries about bugging me, I appreciate people commenting on things they care about on here because it gives me the drive to put in more work :)

**Comment by iamthecrave** [comment]
No, I'm sorry if I bugged you, especially since you're been sick. 

Strange that I'm the only report. Hard to think it's my system, but I guess it might be, though I've tried fresh installs of the module and on different systems, as well as variants of Foundry on both my home computer and Forge. It's bizarre.

I really appreciate your help and will wait patiently. 

Glad you are feeling better.

**Comment by scwalky** [comment]
Hey there - first of all - many many thanks for all the work, second - I can replicate this (didn't report it as I saw it was already on the list).

If I create a new extended task clicking on any field other than Name clears the Name field.

![image](https://user-images.githubusercontent.com/15076930/215099329-d733b968-e65a-4409-9c4b-798dc7c182e4.png)

If I then try and proceed then I get the same validation error.
![image](https://user-images.githubusercontent.com/15076930/215099494-5b16a523-85b5-4af8-be9b-8f2ee4c2e156.png)

Foundry Virtual Tabletop: Version 10, 10.291
Game System: sta, 1.1.9
Active Modules: 19
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 5500 x 3750 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 8 | Tokens: 16

Actors: 60 | Items: 121 | Journal: 42 | Rollable Tables: 8 |
Playlists: 1 | Compendium Packs: 4 | Chat Messages: 811

**Comment by iamthecrave** [comment]
^ Yep that's my experience. And it's not going away!

**Comment by iamthecrave** [comment]
My workaround until it's fixed: put an Extended Task counter on the game map and use token to keep track. It's better than nothing, but I'd prefer the Extended Tasks we used to have!

![image](https://user-images.githubusercontent.com/84590468/219509252-bc64ad8e-adb6-4195-b399-037d707bc775.png)

**Comment by elexisvenator** [comment]
Just had my first one-shot of STA yesterday. This foundry module is great, thanks so much for making this.

We also hit the extended task bug, so I pulled the code and found a fix for it. Let me know if you need any additional changes to land the PR.

**Comment by Mrafala** [comment]
I'm having this same issue. Is there an ETA on a fix?

**Comment by mkscho63** [comment]
Didn't realize that merging the PR would close the issue, but I'm testing the fix from @elexisvenator right now and can hopefully release it later today.

**Comment by mkscho63** [comment]
I have it up on the develop branch now and plan on releasing it with 1.1.10
