### ISSUE TITLE
Bug, or missing Feature? If so. please take this as Suggestion. :D

### ISSUE THREAD

**Issue by x-SubjectZERO-x** [mkscho63/sta#86]
Hello. 
First of all i got to say that i`m really new to Foundry, and aswell your STA module. Your work is really Great, and will be a big help for our ongoing adventures. :) Thank you for that! I hope its understandable what i want to say, because english isn't my native language.

Now for the request/question.
There are Talents wich modify some values. Is it planned to integrate them into the calculations? In Example. The Character has the Talent "Steadfast?", hope its translated correctly, because i only have the the german Core Rulebook. This Talent adds 3 Points to the maximum Stress. But in the Character sheet The Stress Tracker only shows the combined Value of Fitness and Security. And there is no Option to add points. So it also shows the wrong Value at the Character Token.
Maybe a simple Way would be, to add a field to manually increase the Values "+/- X"

Onother Question is:
Maybe i just miss them, but are there any options to track the used/unused Milestones of all three kinds? If not. it would be really cool i you add something like that.

I hope you take this as a constructive comment. Your Work is great, and i look forward to whatever additions you make.

**Comment by mkscho63** [comment]
I will say that the options that increase Stress/Shields/etc SHOULD be handled manually by the system. E.G. if you add a talent named Steadfast then I have some custom handling that will increase the stress threshold for that character. As far as adding support in for active effects like allowing people to control this themselves, I'd love to do it at some point, I just haven't gotten back around to doing any heavy work again lately. Definitely a good idea to have that supported in the system though. Thanks for posting this, I'm always down to hear more feedback, even though I'm slow to work on the system the feedback is still heard and welcome!

**Comment by x-SubjectZERO-x** [comment]
Hey. Its really ok, if you're "slow to work on the System". I think we're all glad it even exists. Grateful for the work you do. Unfortunately i can't find how this should work: -> "E.G. if you add a talent named Steadfast then I have some custom handling that will increase the stress threshold for that character"... Maybe i just understand it wrong. But if i don't misunderstand, you say that it already should work that the points ar added to Stress/Shield, if theres Talents wich should raise them? "Custom Handling?" How should it Work? Wich Option do i have to Choose, that the Points raise?
Sorry for eating up your time.

**Comment by xanstin** [comment]
I was looking into this as well. Looks like if you add the talent which is "Resolute" into the talent list the stress was added automatically. Possible it is a localization issue.
![image](https://github.com/mkscho63/sta/assets/26841771/e45d0446-4518-4481-be78-43739b67c57e)

**Comment by mkscho63** [comment]
Ah yeah that’ll do it. I’ll swap  that around.

**Comment by tokeidlom** [comment]
1.2.1 added the ability to manually adjust stress and shields. Hopefully that means that any cases which weren't captured in the code (or future releases) can be accommodated.

**Comment by tokeidlom** [comment]
Localisation has now been added in, it will go out with the next release (1.2.4), I will also leave the manual adjustment box in place to allow for any new talents that appear, or for house rules anyone may have. It will need the localisation language files to be updated to work, however the functionality is now in there.
