### ISSUE TITLE
Starship Weapons with Include Scale Not Rolling Proper Amount of Challenge Dice

### ISSUE THREAD

**Issue by MrNightwood** [mkscho63/sta#96]
**Describe the bug**
The Include Scale quality added in the recent update is not functioning properly. It does display the proper amount on the actor sheet, however when actually rolling only the number from the Damage field +Security is rolled, ignoring the added dice from the ship's scale.

**To Reproduce**

1. Create a starship weapon with the Include Scale quality checked
2. Add the weapon to a starship sheet with a Scale of at least 1
3. Roll the weapon and compare the amount of dice rolled with the amount listed on the sheet

**Expected behavior**
The weapon should roll a number of challenge dice equal to the damage value + Security + Scale. This should match the quantity listed on the starship sheet.

**Screenshots**
![image](https://github.com/mkscho63/sta/assets/111000735/c2c28e85-5664-4c43-83bd-d8079435463e)

**Comment by mkscho63** [comment]
Aww shoot, that’s right. I’ll take a look at this.

**Comment by tokeidlom** [comment]
Fix for this is rolled into #109

**Comment by tokeidlom** [comment]
Now fully resolved with 1.2.3
