### ISSUE TITLE
Small Craft Container Type Dropdown Displays No Text

### ISSUE THREAD

**Issue by MrNightwood** [mkscho63/sta#97]
**Describe the bug**
The dropdown menu to select the actor sheet to link from a small craft container does not contain any text. The options still appear and function properly, but it is impossible to tell which option is being selected, making it a bit of a guessing game when there is more than one small craft in the world.

**To Reproduce**

1. Create at least one small craft actor sheet
2. Add small craft container to a starship sheet
3.  Open the container's settings and open the Type dropdown

**Expected behavior**
The dropdown menu should display a list of small craft with text visible.

**Screenshots**
![image](https://github.com/mkscho63/sta/assets/111000735/4a09bdcb-b281-4264-8213-6a3cc889fc7a)
![image](https://github.com/mkscho63/sta/assets/111000735/2fe9fcdf-6849-4423-b3a9-6f20997ba7fb)

**Comment by mkscho63** [comment]
Thank you for the report, I’ll take a look

**Comment by mprangenberg** [comment]
I fixed it in #100 😉👍

**Comment by tokeidlom** [comment]
Also partially fixed in #109 however needs refining. Drop-down works properly but name not listed as selected on close/reopen, still retained in the string though. 100 still uses {{#select}} which is annoyingly depreciated in V12, need to switch to {{selectoption}} for a better fix

**Comment by tokeidlom** [comment]
Fully resolved in 1.2.3 release, switched to {{selectoptions}}
