### ISSUE TITLE
Unable to load valid system manifest data... Cannot read properties of undefined (reading 'format')

### ISSUE THREAD

**Issue by DigitalStartupUK** [mkscho63/sta#98]
**Describe the bug**
When attempting to install the Game System via the Foundry VTT Install Window **or** using the Manifest URL directly, an error is produced. As per the screenshot, the message reads:

```
"Error: Unable to load valid system manifest data from "https://raw.githubusercontent.com/mkscho63/sta/master/src/system.json" Cannot read properties of undefined (reading 'format')"
```

**To Reproduce**
1. Go to Install System (in Foundry)
2. Search for "Star Trek"
3. Click "install" on the Star Trek Adventures 2d20 (Unofficial) package
4. Error message occurs

**Expected behavior**
Game System installs successfully

**Screenshots**
![image](https://github.com/mkscho63/sta/assets/24552648/1fc4fe68-10e4-4ad3-b446-7573671d8892)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version N/A
 - Foundry Version 11 Build 305

**Additional context**
I was able to install the package for Pathfinder 2nd Edition without error. So, it is no a global issue.

**Comment by Stanseas** [comment]
Still an issue 8/29. Looking forward to using it.

**Comment by tokeidlom** [comment]
I'm assuming this is resolved now? Unless I hear otherwise I'll close this ticket in a few days.
